#@ load("@ytt:data", "data")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing', 'testing_scanning']) and in_list('profile', ['full', 'iterate', 'build']) and hasattr(data.values, 'pipeline') and data.values.pipeline == 'java':
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tap-java-test-pipeline
  namespace: dev
  labels:
    apps.tanzu.vmware.com/pipeline: test      #! required
    apps.tanzu.vmware.com/language: java
spec:
  params:
    - name: sub-path
    - name: source-url                        #! required
    - name: source-revision                   #! required
  tasks:
    - name: test
      params:
        - name: sub-path
          value: $(params.sub-path)
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: sub-path
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: gradle
            script: |
              cd `mktemp -d`
              #! wget -qO- $(params.source-url) | tar xvz -m
              #! cd tanzu-java-web-app
              #! gradle test 
