apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: react-frontend
  annotations:
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
    ootb.apps.tanzu.vmware.com/apidescriptor-ref: "true"
    kapp.k14s.io/change-rule: upsert after upserting servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: react-frontend
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: react-frontend
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"react-frontend","apps.tanzu.vmware.com/workload-type":"web"},"name":"react-frontend","namespace":"dev"},"spec":{"build":{"env":[{"name":"BP_NODE_RUN_SCRIPTS","value":"build"},{"name":"BP_WEB_SERVER_ROOT","value":"build"}]},"params":[{"name":"annotations","value":{"autoscaling.knative.dev/minScale":"1"}},{"name":"clusterBuilder","value":"default"}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/pivotal-ben-chacko/application-accelerators.git"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: react-frontend
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: react-frontend
    spec:
      containers:
      - image: harbor.skynetsystems.io/tap/workloads/react-frontend-dev@sha256:ef0fbc95673aafa2c2b74cc673aa6b2bf3e44665bea41ffd1e73cc5e242c91db
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

